{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "10dd98f8-fdf3-40a3-95d5-b5df4dcb863b",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": [
    "from rich import print\n",
    "import random\n",
    "import secrets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "937e653f-b3cb-4cb9-ae81-ba1bcc2375f5",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": [
    "python_topics = {\n",
    "    # Basics\n",
    "    \"Variables and Data Types\": \"Store and manipulate different types of data like integers, floats, strings, etc.\",\n",
    "    \"Comments\": \"Used to annotate code for better readability, ignored during execution.\",\n",
    "    \"Input and Output\": \"Take user input and display output using input() and print().\",\n",
    "    \"Operators (Arithmetic, Comparison, Logical, etc.)\": \"Perform operations like addition, comparisons, and logical decisions.\",\n",
    "    \"Type Casting\": \"Convert a variable from one data type to another.\",\n",
    "    \"String Operations\": \"Manipulate and handle text using various string methods and operators.\",\n",
    "    \n",
    "    # Control Flow\n",
    "    \"if, elif, else Statements\": \"Control execution flow based on conditions.\",\n",
    "    \"for Loops\": \"Iterate over a sequence like list, string, or range.\",\n",
    "    \"while Loops\": \"Repeat a block of code while a condition is True.\",\n",
    "    \"break and continue\": \"Alter loop execution by breaking out or skipping to the next iteration.\",\n",
    "    \"pass Statement\": \"A placeholder statement that does nothing.\",\n",
    "    \n",
    "    # Data Structures\n",
    "    \"Lists\": \"Ordered, mutable collection of items.\",\n",
    "    \"Tuples\": \"Ordered, immutable collection of items.\",\n",
    "    \"Sets\": \"Unordered collection of unique items.\",\n",
    "    \"Dictionaries\": \"Key-value pairs used for fast lookups.\",\n",
    "    \"List Comprehensions\": \"Concise way to create lists using a single line of code.\",\n",
    "    \"Dictionary Comprehensions\": \"Compact way to create dictionaries from iterables.\",\n",
    "    \n",
    "    # Functions\n",
    "    \"Defining Functions\": \"Encapsulate reusable blocks of code using def keyword.\",\n",
    "    \"Return Statement\": \"Send back a result from a function to the caller.\",\n",
    "    \"Arguments and Parameters\": \"Input values passed to functions to customize behavior.\",\n",
    "    \"Default and Keyword Arguments\": \"Provide default values and named arguments in functions.\",\n",
    "    \"Variable-length Arguments (*args, **kwargs)\": \"Allow passing variable number of arguments to functions.\",\n",
    "    \"Lambda Functions\": \"Create small anonymous functions in a single line.\",\n",
    "    \"Recursion\": \"A function calling itself to solve smaller instances of a problem.\",\n",
    "    \n",
    "    # Modules and Packages\n",
    "    \"Importing Modules\": \"Reuse existing code by importing Python files or libraries.\",\n",
    "    \"Built-in Modules (math, random, datetime, etc.)\": \"Modules included with Python to perform common tasks.\",\n",
    "    \"Creating and Using Packages\": \"Organize and reuse code using module directories.\",\n",
    "    \n",
    "    # File Handling\n",
    "    \"Reading and Writing Files\": \"Open, read, write, and close files using file operations.\",\n",
    "    \"with Statement (Context Managers)\": \"Handle resources like files efficiently using context managers.\",\n",
    "    \"Working with Text and Binary Files\": \"Read and write both text and non-text files (like images).\",\n",
    "    \n",
    "    # Exception Handling\n",
    "    \"try, except\": \"Catch and handle runtime errors gracefully.\",\n",
    "    \"finally\": \"Execute code after try/except blocks, regardless of what happened.\",\n",
    "    \"raise\": \"Manually trigger an exception.\",\n",
    "    \"Custom Exceptions\": \"Define your own error types by extending Exception class.\",\n",
    "    \n",
    "    # Object-Oriented Programming (OOP)\n",
    "    \"Classes and Objects\": \"Bundle data and methods into reusable blueprints and instances.\",\n",
    "    \"Constructors (__init__)\": \"Initialize objects when a class is instantiated.\",\n",
    "    \"Instance and Class Variables\": \"Store data that’s specific to an object or shared across class.\",\n",
    "    \"Methods (Instance, Class, Static)\": \"Functions associated with class and object behavior.\",\n",
    "    \"Inheritance\": \"Create new classes based on existing ones to reuse functionality.\",\n",
    "    \"Polymorphism\": \"Use a common interface for different data types or classes.\",\n",
    "    \"Encapsulation\": \"Restrict access to parts of an object for data protection.\",\n",
    "    \"Magic/Dunder Methods (__str__, __len__, etc.)\": \"Special methods used to define object behavior with built-in operations.\",\n",
    "    \n",
    "    # Advanced Data Structures\n",
    "    \"Stacks and Queues\": \"Abstract data types used for LIFO and FIFO operations respectively.\",\n",
    "    \"Linked Lists\": \"Linear collection of nodes where each points to the next.\",\n",
    "    \"Trees\": \"Hierarchical data structure with nodes and parent-child relationships.\",\n",
    "    \"Graphs\": \"Set of nodes connected by edges, useful in networked data.\",\n",
    "    \n",
    "    # Iterators and Generators\n",
    "    \"__iter__ and __next__\": \"Enable custom iteration over objects using iterator protocol.\",\n",
    "    \"Generator Functions (yield)\": \"Create iterators lazily with yield instead of return.\",\n",
    "    \n",
    "    # Decorators and Closures\n",
    "    \"Function Closures\": \"Functions that capture and remember variables from their scope.\",\n",
    "    \"Decorators (Function and Class Based)\": \"Modify or enhance functions and classes using @ syntax.\",\n",
    "    \n",
    "    # Regular Expressions (re module)\n",
    "    \"re.match, re.search, re.fullmatch\": \"Match patterns in strings using regular expressions.\",\n",
    "    \"re.findall, re.sub, re.compile\": \"Find, replace, or compile regex patterns for reuse.\",\n",
    "    \n",
    "    # Comprehensions and Functional Tools\n",
    "    \"map(), filter(), reduce()\": \"Functional tools to transform and filter data.\",\n",
    "    \"zip() and enumerate()\": \"Pair elements and get index-value pairs in loops.\",\n",
    "    \"all() and any()\": \"Check if all or any elements in an iterable satisfy a condition.\",\n",
    "    \n",
    "    # Working with Dates and Times\n",
    "    \"datetime module\": \"Work with dates, times, and timestamps.\",\n",
    "    \"time module\": \"Measure time intervals and access system time.\",\n",
    "    \n",
    "    # Working with JSON\n",
    "    \"json module\": \"Parse and generate JSON data for APIs and configs.\",\n",
    "    \n",
    "    # Pythonic Conventions\n",
    "    \"PEP8\": \"Official style guide for writing clean Python code.\",\n",
    "    \"Docstrings\": \"Describe the purpose of functions, classes, and modules.\",\n",
    "    \"Unpacking (*, **)\": \"Expand iterables and dictionaries into arguments or assignments.\",\n",
    "    \n",
    "    # Virtual Environments & Packaging\n",
    "    \"venv and pip\": \"Create isolated environments and manage dependencies.\",\n",
    "    \"requirements.txt\": \"List of project dependencies for reproducibility.\",\n",
    "    \"setup.py and packaging projects\": \"Configuration file for packaging and distributing Python libraries.\",\n",
    "    \n",
    "    # Testing\n",
    "    \"assert Statements\": \"Check conditions in code, used in testing.\",\n",
    "    \"unittest Module\": \"Built-in framework for writing and running tests.\",\n",
    "    \"pytest (3rd party)\": \"Popular external framework for writing simple and powerful tests.\",\n",
    "    \n",
    "    # Debugging and Profiling\n",
    "    \"pdb (Python Debugger)\": \"Step through and inspect code during execution.\",\n",
    "    \"timeit and cProfile modules\": \"Measure execution time and profile performance.\",\n",
    "    \n",
    "    # Concurrency\n",
    "    \"Multithreading\": \"Run multiple threads to perform tasks concurrently.\",\n",
    "    \"Multiprocessing\": \"Leverage multiple CPU cores by running separate processes.\",\n",
    "    \"Asyncio and Coroutines\": \"Handle asynchronous I/O with async/await syntax.\",\n",
    "    \n",
    "    # Web and Networking (Intro)\n",
    "    \"HTTP Requests (requests module)\": \"Send HTTP requests and handle responses easily.\",\n",
    "    \"Socket Programming\": \"Build networked applications with low-level socket interfaces.\",\n",
    "    \n",
    "    # Database Interaction\n",
    "    \"SQLite (sqlite3 module)\": \"Lightweight database included with Python for local storage.\",\n",
    "    \"MySQL or PostgreSQL (using connectors)\": \"Connect and interact with external SQL databases.\",\n",
    "    \n",
    "    # File Formats\n",
    "    \"CSV files (csv module)\": \"Read from and write to CSV files.\",\n",
    "    \"Excel files (pandas, openpyxl)\": \"Handle Excel files for reading and writing spreadsheets.\",\n",
    "    \"PDF and Word (PyPDF2, python-docx)\": \"Manipulate PDF and Word documents using libraries.\",\n",
    "    \n",
    "    # External Libraries (Intro)\n",
    "    \"NumPy\": \"Library for numerical operations and arrays.\",\n",
    "    \"Pandas\": \"Data analysis and manipulation library with DataFrame structure.\",\n",
    "    \"Matplotlib\": \"Plotting library to create static, animated, and interactive charts.\",\n",
    "    \"Flask/Django (Web Frameworks)\": \"Frameworks for building web applications with Python.\",\n",
    "    \n",
    "    # Python Internals\n",
    "    \"Memory Management\": \"How Python allocates and deallocates memory automatically.\",\n",
    "    \"Namespaces and Scope\": \"Define the visibility and lifetime of variables.\",\n",
    "    \"Garbage Collection\": \"Automatic cleanup of unused objects to free memory.\",\n",
    "    \"Compilation vs Interpretation\": \"How Python executes code through interpretation and optional compilation.\",\n",
    "    \n",
    "    # Miscellaneous\n",
    "    \"Assertions\": \"Sanity-checks used to verify assumptions in code.\",\n",
    "    \"Type Hinting\": \"Specify expected data types for variables and functions.\",\n",
    "    \"Pattern Matching (match-case)\": \"Match data structures and values with structural pattern matching.\",\n",
    "    \"Command-Line Arguments (argparse)\": \"Parse command-line options and arguments for scripts.\"\n",
    "}\n",
    "\n",
    "machine_learning_topics = {\n",
    "    # Basics and Foundations\n",
    "    \"Introduction to Machine Learning\": \"Understanding how machines learn from data to make predictions or decisions.\",\n",
    "    \"Types of Machine Learning (Supervised, Unsupervised, Reinforcement)\": \"Different learning paradigms based on data labeling and interaction with the environment.\",\n",
    "    \"Bias-Variance Tradeoff\": \"Balancing model complexity to minimize both bias and variance errors.\",\n",
    "    \"Overfitting and Underfitting\": \"When a model learns too much or too little from the training data.\",\n",
    "    \"Training, Validation, and Testing Data\": \"Splitting data to train models and evaluate their performance fairly.\",\n",
    "    \"Evaluation Metrics (Accuracy, Precision, Recall, F1 Score, ROC-AUC)\": \"Metrics to assess model performance across various tasks and class imbalances.\",\n",
    "    \n",
    "    # Data Preprocessing\n",
    "    \"Data Cleaning\": \"Removing or fixing incorrect, incomplete, or duplicate data.\",\n",
    "    \"Handling Missing Values\": \"Techniques to deal with absent data in datasets.\",\n",
    "    \"Feature Scaling (Normalization, Standardization)\": \"Rescaling features to ensure uniform model learning.\",\n",
    "    \"Feature Engineering\": \"Creating new relevant features to improve model performance.\",\n",
    "    \"Dimensionality Reduction (PCA, t-SNE)\": \"Reducing the number of input features while preserving information.\",\n",
    "    \"Data Splitting (Train/Test/Validation)\": \"Dividing data to train, tune, and test the model properly.\",\n",
    "    \n",
    "    # Supervised Learning Algorithms\n",
    "    \"Linear Regression\": \"Modeling the relationship between features and a continuous outcome.\",\n",
    "    \"Logistic Regression\": \"Predicting binary outcomes using a logistic function.\",\n",
    "    \"Decision Trees\": \"Tree-like models that split data based on feature conditions.\",\n",
    "    \"Random Forests\": \"An ensemble of decision trees to improve prediction accuracy.\",\n",
    "    \"Gradient Boosting Machines (XGBoost, LightGBM, CatBoost)\": \"Ensemble models that build trees sequentially to correct previous errors.\",\n",
    "    \"Support Vector Machines (SVM)\": \"Finding the optimal hyperplane to separate classes in feature space.\",\n",
    "    \"K-Nearest Neighbors (KNN)\": \"Predicting outcomes based on the majority vote of nearby points.\",\n",
    "    \"Naive Bayes Classifier\": \"A probabilistic classifier based on Bayes' theorem with independence assumptions.\",\n",
    "    \n",
    "    # Unsupervised Learning Algorithms\n",
    "    \"K-Means Clustering\": \"Grouping data into clusters based on feature similarity.\",\n",
    "    \"Hierarchical Clustering\": \"Building a tree of clusters based on data similarity.\",\n",
    "    \"DBSCAN\": \"Density-based clustering that groups closely packed points.\",\n",
    "    \"Gaussian Mixture Models\": \"Probabilistic model assuming data is from a mixture of Gaussians.\",\n",
    "    \"Principal Component Analysis (PCA)\": \"A linear method to reduce feature dimensions.\",\n",
    "    \"Anomaly Detection\": \"Identifying rare or unusual data patterns.\",\n",
    "    \n",
    "    # Neural Networks and Deep Learning\n",
    "    \"Perceptron\": \"The simplest neural network unit used for binary classification.\",\n",
    "    \"Feedforward Neural Networks\": \"Neural networks where connections move only forward from input to output.\",\n",
    "    \"Activation Functions (ReLU, Sigmoid, Tanh)\": \"Functions that add non-linearity to neural networks.\",\n",
    "    \"Backpropagation\": \"An algorithm to update weights using gradient descent in neural networks.\",\n",
    "    \"Convolutional Neural Networks (CNNs)\": \"Specialized networks for processing grid-like data such as images.\",\n",
    "    \"Recurrent Neural Networks (RNNs)\": \"Neural networks with loops to process sequential data.\",\n",
    "    \"Long Short-Term Memory (LSTM)\": \"A type of RNN that can remember long-term dependencies.\",\n",
    "    \"Autoencoders\": \"Neural networks used to learn efficient data encodings.\",\n",
    "    \"Generative Adversarial Networks (GANs)\": \"Two neural networks that compete to generate realistic data.\",\n",
    "    \n",
    "    # Model Optimization and Training\n",
    "    \"Gradient Descent and Variants (SGD, Adam, RMSProp)\": \"Optimization algorithms used to minimize loss functions.\",\n",
    "    \"Loss Functions (MSE, Cross-Entropy)\": \"Functions that quantify how far off predictions are from actual values.\",\n",
    "    \"Regularization Techniques (L1, L2, Dropout)\": \"Methods to prevent overfitting by penalizing model complexity.\",\n",
    "    \"Hyperparameter Tuning (Grid Search, Random Search, Bayesian Optimization)\": \"Searching for the best model parameters.\",\n",
    "    \"Early Stopping\": \"Halting training once performance stops improving on validation data.\",\n",
    "    \n",
    "    # Evaluation and Validation\n",
    "    \"Cross-Validation (k-fold, stratified)\": \"Technique to validate models across multiple train/test splits.\",\n",
    "    \"Confusion Matrix\": \"A matrix to visualize the performance of classification models.\",\n",
    "    \"ROC and AUC Curves\": \"Tools to evaluate classification performance across thresholds.\",\n",
    "    \n",
    "    # Advanced Topics\n",
    "    \"Reinforcement Learning Basics\": \"Learning to make decisions via trial and error in an environment.\",\n",
    "    \"Q-Learning\": \"A reinforcement learning algorithm using Q-values to learn policies.\",\n",
    "    \"Policy Gradients\": \"RL technique that optimizes the policy directly via gradients.\",\n",
    "    \"Transfer Learning\": \"Using a pretrained model on one task to accelerate learning on another.\",\n",
    "    \"Ensemble Learning\": \"Combining multiple models to improve predictions.\",\n",
    "    \"Explainable AI (XAI)\": \"Techniques to make ML model decisions interpretable.\",\n",
    "    \n",
    "    # Tools and Libraries\n",
    "    \"NumPy and Pandas\": \"Core Python libraries for numerical and tabular data processing.\",\n",
    "    \"Matplotlib and Seaborn for Visualization\": \"Libraries to create data visualizations and plots.\",\n",
    "    \"Scikit-learn\": \"A machine learning library with tools for model building and evaluation.\",\n",
    "    \"TensorFlow\": \"An open-source deep learning framework developed by Google.\",\n",
    "    \"PyTorch\": \"A popular deep learning library known for its dynamic computation graph.\",\n",
    "    \n",
    "    # Practical Considerations\n",
    "    \"Data Ethics and Bias\": \"Ensuring fairness, accountability, and transparency in ML systems.\",\n",
    "    \"Model Deployment\": \"Integrating trained models into production environments.\",\n",
    "    \"Scaling ML Models\": \"Handling large-scale data and infrastructure in ML pipelines.\",\n",
    "    \"Version Control for ML (MLflow, DVC)\": \"Tracking ML experiments, data, and models over time.\",\n",
    "    \n",
    "    # Others\n",
    "    \"Natural Language Processing (NLP)\": \"Techniques to process and understand human language data.\",\n",
    "    \"Computer Vision\": \"Enabling machines to interpret and understand visual data.\",\n",
    "    \"Time Series Analysis\": \"Analyzing data points indexed in time order.\",\n",
    "    \"Recommender Systems\": \"Algorithms that suggest items based on user preferences.\"\n",
    "}\n",
    "\n",
    "sql_topics = {\n",
    "    # Basics\n",
    "    \"What is SQL\": \"SQL is a language for managing and querying relational databases.\",\n",
    "    \"SQL Syntax and Keywords\": \"Defines how SQL commands are written using reserved words and structure.\",\n",
    "    \"SQL Data Types\": \"Defines the type of data a column can hold, like INT, VARCHAR, DATE, etc.\",\n",
    "    \"CREATE, ALTER, DROP (DDL Commands)\": \"Commands to define and modify database schema objects.\",\n",
    "    \"INSERT, UPDATE, DELETE (DML Commands)\": \"Used to manipulate data within tables.\",\n",
    "    \"SELECT Statement\": \"Retrieves data from one or more tables.\",\n",
    "    \"WHERE Clause\": \"Filters records based on specified conditions.\",\n",
    "    \"ORDER BY\": \"Sorts the result set by one or more columns.\",\n",
    "    \"LIMIT / TOP / FETCH\": \"Restricts the number of rows returned by a query.\",\n",
    "\n",
    "    # Filtering and Operators\n",
    "    \"Comparison Operators (=, <>, >, <, etc.)\": \"Used to compare values in WHERE clauses.\",\n",
    "    \"BETWEEN, IN, LIKE\": \"Operators for range, set, and pattern matching filtering.\",\n",
    "    \"IS NULL and IS NOT NULL\": \"Checks if a column has missing (null) values.\",\n",
    "    \"Logical Operators (AND, OR, NOT)\": \"Combine multiple conditions in WHERE clauses.\",\n",
    "\n",
    "    # Functions\n",
    "    \"Aggregate Functions (COUNT, SUM, AVG, MAX, MIN)\": \"Performs calculations across rows of data.\",\n",
    "    \"String Functions (UPPER, LOWER, CONCAT, LENGTH)\": \"Manipulates and evaluates string data.\",\n",
    "    \"Date and Time Functions\": \"Works with date/time values for calculations and formatting.\",\n",
    "    \"Mathematical Functions\": \"Performs arithmetic or mathematical operations on data.\",\n",
    "\n",
    "    # Joins\n",
    "    \"INNER JOIN\": \"Returns rows with matching values in both tables.\",\n",
    "    \"LEFT JOIN (LEFT OUTER JOIN)\": \"Returns all rows from the left table, with matched rows from the right.\",\n",
    "    \"RIGHT JOIN (RIGHT OUTER JOIN)\": \"Returns all rows from the right table, with matched rows from the left.\",\n",
    "    \"FULL JOIN (FULL OUTER JOIN)\": \"Returns all rows when there is a match in one of the tables.\",\n",
    "    \"CROSS JOIN\": \"Returns the Cartesian product of two tables.\",\n",
    "    \"Self JOIN\": \"Joins a table to itself using aliases.\",\n",
    "\n",
    "    # Grouping and Aggregation\n",
    "    \"GROUP BY\": \"Groups rows that share values into summary rows.\",\n",
    "    \"HAVING Clause\": \"Filters grouped rows after aggregation.\",\n",
    "    \"ROLLUP and CUBE (Advanced Grouping)\": \"Performs multi-level aggregations in a single query.\",\n",
    "\n",
    "    # Subqueries\n",
    "    \"Subqueries in WHERE Clause\": \"Nested queries used to filter rows in the outer query.\",\n",
    "    \"Subqueries in SELECT Clause\": \"Nested queries used to compute values in the result set.\",\n",
    "    \"Correlated Subqueries\": \"Subqueries that reference columns from the outer query.\",\n",
    "    \"EXISTS and NOT EXISTS\": \"Checks for the existence of rows returned by a subquery.\",\n",
    "\n",
    "    # Set Operations\n",
    "    \"UNION and UNION ALL\": \"Combines results of multiple SELECTs; UNION removes duplicates.\",\n",
    "    \"INTERSECT\": \"Returns rows common to both SELECT queries.\",\n",
    "    \"EXCEPT / MINUS\": \"Returns rows from the first SELECT not present in the second.\",\n",
    "\n",
    "    # Constraints and Keys\n",
    "    \"Primary Key\": \"Uniquely identifies each row in a table.\",\n",
    "    \"Foreign Key\": \"Establishes a link between two tables.\",\n",
    "    \"Unique Constraint\": \"Ensures all values in a column are unique.\",\n",
    "    \"NOT NULL\": \"Ensures that a column cannot contain null values.\",\n",
    "    \"CHECK Constraint\": \"Enforces a condition on data values.\",\n",
    "    \"DEFAULT Values\": \"Specifies a default value when no value is provided.\",\n",
    "\n",
    "    # Indexes and Performance\n",
    "    \"Indexes\": \"Improves query performance by enabling faster data access.\",\n",
    "    \"Clustered vs Non-clustered Index\": \"Clustered sorts table rows; non-clustered is a separate structure.\",\n",
    "    \"Query Optimization Basics\": \"Techniques to improve the efficiency of SQL queries.\",\n",
    "    \"EXPLAIN / EXPLAIN PLAN\": \"Shows the execution plan of a SQL query.\",\n",
    "\n",
    "    # Views and Stored Objects\n",
    "    \"Views\": \"Virtual tables based on the result of a SQL query.\",\n",
    "    \"Stored Procedures\": \"Reusable SQL blocks that can include control flow and parameters.\",\n",
    "    \"Functions\": \"Reusable SQL blocks that return a value.\",\n",
    "    \"Triggers\": \"Procedures that execute automatically in response to certain events.\",\n",
    "    \"Cursors\": \"Used to iterate over query results row-by-row.\",\n",
    "\n",
    "    # Transactions and ACID\n",
    "    \"BEGIN, COMMIT, ROLLBACK\": \"Controls transactions by grouping operations and ensuring atomicity.\",\n",
    "    \"ACID Properties\": \"Atomicity, Consistency, Isolation, Durability ensure reliable transactions.\",\n",
    "    \"Transaction Isolation Levels\": \"Defines how transactions interact with each other.\",\n",
    "\n",
    "    # User Management & Security\n",
    "    \"GRANT and REVOKE\": \"Manages user permissions on database objects.\",\n",
    "    \"User Roles and Permissions\": \"Controls what actions users can perform within the database.\",\n",
    "\n",
    "    # Advanced Topics\n",
    "    \"Window Functions (OVER, PARTITION BY)\": \"Performs calculations across rows related to the current row.\",\n",
    "    \"Common Table Expressions (CTEs)\": \"Temporary named result sets used within a query.\",\n",
    "    \"Recursive Queries\": \"CTEs that reference themselves for hierarchical data.\",\n",
    "    \"Pivot and Unpivot\": \"Transforms rows into columns and vice versa.\",\n",
    "    \"JSON and XML Handling in SQL\": \"Working with structured data stored in JSON or XML format.\",\n",
    "    \"Working with NULLs\": \"Special handling and comparisons of null (missing) values.\",\n",
    "    \"Temporal Tables (System-Versioned)\": \"Tracks historical changes in data over time.\",\n",
    "\n",
    "    # Tools and Environments\n",
    "    \"SQL in MySQL\": \"SQL syntax and features as implemented in MySQL.\",\n",
    "    \"SQL in PostgreSQL\": \"Advanced SQL features and extensions in PostgreSQL.\",\n",
    "    \"SQL in SQLite\": \"Lightweight SQL engine used in mobile and embedded systems.\",\n",
    "    \"SQL in SQL Server\": \"Microsoft’s SQL implementation with T-SQL extensions.\",\n",
    "    \"SQL in Oracle\": \"Enterprise-level SQL with powerful PL/SQL features.\",\n",
    "\n",
    "    # Practical Use Cases\n",
    "    \"Designing Relational Databases\": \"Structuring data in tables with relationships and constraints.\",\n",
    "    \"Normalization and Denormalization\": \"Organizing data to reduce redundancy or optimize performance.\",\n",
    "    \"Data Modeling (ER Diagrams)\": \"Visual representation of data entities and their relationships.\",\n",
    "    \"Backup and Restore\": \"Processes for saving and recovering database data.\",\n",
    "    \"Data Migration and ETL with SQL\": \"Moving and transforming data between systems using SQL.\",\n",
    "}\n",
    "\n",
    "power_bi_topics = {\n",
    "    # Introduction & Basics\n",
    "    \"What is Power BI\": \"Power BI is a business analytics tool for transforming data into interactive insights.\",\n",
    "    \"Power BI Components (Desktop, Service, Mobile, Report Server)\": \"The core tools for creating, sharing, and accessing Power BI reports across platforms.\",\n",
    "    \"Power BI Workflow (Import, Transform, Visualize, Share)\": \"The end-to-end process of building and sharing Power BI reports.\",\n",
    "    \"Power BI Interface Overview\": \"A tour of the Power BI Desktop interface including ribbons, panes, and views.\",\n",
    "\n",
    "    # Data Sources & Loading\n",
    "    \"Connecting to Data Sources (Excel, SQL Server, Web, etc.)\": \"Import data from various sources into Power BI for analysis.\",\n",
    "    \"Import vs DirectQuery vs Live Connection\": \"Different methods of data connectivity and their performance implications.\",\n",
    "    \"Refreshing Data\": \"Updating datasets to reflect the latest changes in the source data.\",\n",
    "    \"Query Folding\": \"The process of pushing transformations back to the source to improve efficiency.\",\n",
    "\n",
    "    # Power Query & Data Transformation\n",
    "    \"Power Query Editor\": \"The interface used for data transformation and shaping before modeling.\",\n",
    "    \"Basic Transformations (Remove Columns, Filter, Rename)\": \"Essential steps for cleaning and organizing your dataset.\",\n",
    "    \"Merging and Appending Queries\": \"Combining data from multiple tables into one using joins or unions.\",\n",
    "    \"Unpivot and Pivot Columns\": \"Transforming column-oriented data into row format and vice versa.\",\n",
    "    \"Creating Custom Columns\": \"Adding calculated columns using Power Query or M code.\",\n",
    "    \"Handling Nulls and Errors\": \"Techniques to deal with missing or problematic data values.\",\n",
    "    \"Data Types and Formatting\": \"Setting appropriate data types for accurate analysis and visuals.\",\n",
    "    \"M Language Basics\": \"An introduction to the M formula language used in Power Query.\",\n",
    "\n",
    "    # Data Modeling\n",
    "    \"Data Relationships (1-to-many, many-to-many)\": \"Defining how tables relate to each other in a data model.\",\n",
    "    \"Star Schema vs Snowflake Schema\": \"Different ways to structure data for performance and clarity.\",\n",
    "    \"Primary and Foreign Keys\": \"Keys used to link relational data across tables.\",\n",
    "    \"Managing Relationships\": \"Creating and editing relationships between tables in Power BI.\",\n",
    "    \"Role-playing Dimensions\": \"Reusing a single dimension table for multiple roles (e.g., order date vs. ship date).\",\n",
    "\n",
    "    # DAX (Data Analysis Expressions)\n",
    "    \"Calculated Columns vs Measures\": \"Understanding when to use column-level vs aggregate-level calculations.\",\n",
    "    \"DAX Syntax and Functions\": \"The basics of writing formulas in Power BI's DAX language.\",\n",
    "    \"Common DAX Functions (SUM, AVERAGE, COUNT, CALCULATE)\": \"Frequent functions used for aggregations and logic in DAX.\",\n",
    "    \"Time Intelligence Functions\": \"Functions that simplify calculations across time periods.\",\n",
    "    \"FILTER, ALL, RELATED, RELATEDTABLE\": \"Advanced DAX functions for manipulating context and relationships.\",\n",
    "    \"IF, SWITCH, VAR\": \"Conditional logic and variable definitions in DAX.\",\n",
    "    \"DAX Context (Row Context vs Filter Context)\": \"Understanding how data context affects DAX calculations.\",\n",
    "    \"Error Handling in DAX\": \"Managing errors and null values within DAX formulas.\",\n",
    "\n",
    "    # Data Visualization\n",
    "    \"Creating Visuals (Tables, Cards, Charts, Maps, etc.)\": \"Building compelling visuals from your data model.\",\n",
    "    \"Custom Visuals\": \"Importing and using visuals beyond the default Power BI options.\",\n",
    "    \"Using Slicers and Filters\": \"Interactive tools to slice and filter report data.\",\n",
    "    \"Drill Down, Drill Through, and Hierarchies\": \"Navigating multi-level data using drill actions and hierarchies.\",\n",
    "    \"Bookmarks and Buttons\": \"Adding interactivity and navigation to Power BI reports.\",\n",
    "    \"Themes and Formatting\": \"Customizing visual styles and report appearance.\",\n",
    "    \"Tooltips and Conditional Formatting\": \"Adding dynamic info and styling based on data values.\",\n",
    "    \"Grouping and Binning\": \"Segmenting continuous data into categories for analysis.\",\n",
    "\n",
    "    # Power BI Service\n",
    "    \"Publishing Reports to Power BI Service\": \"Uploading Power BI reports for online access and sharing.\",\n",
    "    \"Creating and Sharing Dashboards\": \"Combining multiple visuals into a unified dashboard experience.\",\n",
    "    \"Workspaces and Apps\": \"Organizing, developing, and sharing content in collaborative environments.\",\n",
    "    \"Datasets, Reports, and Dashboards Differences\": \"Clarifying the components of a Power BI solution.\",\n",
    "    \"Data Gateway Setup\": \"Enabling on-premises data sources to refresh in the cloud.\",\n",
    "    \"Scheduled Refresh\": \"Automatically updating reports with fresh data at set intervals.\",\n",
    "    \"Row-Level Security (RLS)\": \"Restricting data access based on user roles.\",\n",
    "    \"Usage Metrics and Report Insights\": \"Monitoring report performance and user engagement.\",\n",
    "\n",
    "    # Power BI Advanced Features\n",
    "    \"Power BI Paginated Reports\": \"Pixel-perfect, printable reports built with Report Builder.\",\n",
    "    \"Power BI Goals\": \"Tracking and aligning business objectives within Power BI.\",\n",
    "    \"Deployment Pipelines\": \"Managing report lifecycle from development to production.\",\n",
    "    \"Power BI Report Builder\": \"Tool for designing paginated reports with fine-grained layout control.\",\n",
    "    \"Using Python or R in Power BI\": \"Executing advanced analytics and visualizations using Python or R scripts.\",\n",
    "    \"Power BI REST API (Intro)\": \"Programmatically interact with Power BI resources for automation.\",\n",
    "    \"Power BI Embedded (for Developers)\": \"Embedding Power BI visuals in custom applications for users.\",\n",
    "\n",
    "    # Performance Optimization\n",
    "    \"Optimizing Data Models\": \"Improving performance by refining tables, relationships, and data granularity.\",\n",
    "    \"Reducing Dataset Size\": \"Techniques to limit file size for faster load and refresh times.\",\n",
    "}\n",
    "\n",
    "\n",
    "nlp_topics = {\n",
    "    # Introduction\n",
    "    \"What is NLP\": \"NLP enables machines to understand, interpret, and generate human language.\",\n",
    "    \"Applications of NLP\": \"NLP is used in chatbots, translation, sentiment analysis, and more.\",\n",
    "    \"Challenges in NLP\": \"Ambiguity, context, sarcasm, and data sparsity make NLP difficult.\",\n",
    "    \"NLP vs NLU vs NLG\": \"NLP is broad, NLU focuses on understanding, NLG on language generation.\",\n",
    "\n",
    "    # Text Preprocessing\n",
    "    \"Text Normalization\": \"Standardizing text to reduce variation and improve consistency.\",\n",
    "    \"Tokenization\": \"Splitting text into individual words, sentences, or subwords.\",\n",
    "    \"Lowercasing\": \"Converting all text to lowercase to avoid case sensitivity issues.\",\n",
    "    \"Stop Words Removal\": \"Removing common words that may not add meaningful information.\",\n",
    "    \"Stemming\": \"Reducing words to their root form by chopping off endings.\",\n",
    "    \"Lemmatization\": \"Converting words to their dictionary form based on context.\",\n",
    "    \"Punctuation and Special Characters Removal\": \"Cleaning text by removing unwanted symbols.\",\n",
    "    \"Regex for Text Cleaning\": \"Using regular expressions to identify and clean patterns in text.\",\n",
    "\n",
    "    # Text Representation\n",
    "    \"Bag of Words (BoW)\": \"Representing text by word counts without considering order.\",\n",
    "    \"TF-IDF (Term Frequency–Inverse Document Frequency)\": \"Weighting words based on their frequency and uniqueness.\",\n",
    "    \"N-grams\": \"Sequences of n contiguous words used for capturing context.\",\n",
    "    \"One-Hot Encoding\": \"Binary representation of words where each word is a unique vector.\",\n",
    "    \"Word Embeddings (Word2Vec, GloVe, FastText)\": \"Dense vector representations capturing word semantics.\",\n",
    "    \"Contextual Embeddings (ELMo, BERT, etc.)\": \"Dynamic embeddings based on word context within sentences.\",\n",
    "\n",
    "    # NLP Tasks\n",
    "    \"Text Classification\": \"Assigning categories to text based on content.\",\n",
    "    \"Sentiment Analysis\": \"Detecting emotions or opinions in text.\",\n",
    "    \"Named Entity Recognition (NER)\": \"Identifying proper nouns like people, places, and organizations.\",\n",
    "    \"Part-of-Speech (POS) Tagging\": \"Labeling words with their grammatical roles.\",\n",
    "    \"Text Summarization\": \"Condensing text to its essential information.\",\n",
    "    \"Text Generation\": \"Creating new, coherent text based on learned patterns.\",\n",
    "    \"Question Answering\": \"Answering questions based on given context or documents.\",\n",
    "    \"Machine Translation\": \"Automatically translating text from one language to another.\",\n",
    "    \"Topic Modeling (LDA, NMF)\": \"Discovering abstract topics within a collection of texts.\",\n",
    "    \"Text Similarity\": \"Measuring how similar two texts are in meaning or content.\",\n",
    "    \"Language Modeling\": \"Predicting the next word in a sequence based on context.\",\n",
    "    \"Speech Recognition and Synthesis\": \"Converting speech to text and text to speech.\",\n",
    "\n",
    "    # Syntax and Structure\n",
    "    \"Syntax Trees (Parse Trees)\": \"Tree structures representing grammatical structure of sentences.\",\n",
    "    \"Dependency Parsing\": \"Identifying grammatical relationships between words in a sentence.\",\n",
    "    \"Chunking\": \"Grouping words into meaningful phrases (like noun or verb phrases).\",\n",
    "    \"POS Tagging Algorithms\": \"Algorithms for assigning grammatical tags to words in context.\",\n",
    "\n",
    "    # NLP with Machine Learning\n",
    "    \"Supervised Learning for Text Classification\": \"Using labeled data to train text classifiers.\",\n",
    "    \"Naive Bayes for NLP\": \"Probabilistic model based on word frequency and Bayes' theorem.\",\n",
    "    \"Support Vector Machines (SVM)\": \"Classifier that finds the optimal margin between text classes.\",\n",
    "    \"Logistic Regression for NLP\": \"Linear model to classify text based on feature weights.\",\n",
    "    \"Deep Learning for NLP (RNNs, CNNs, LSTMs)\": \"Neural networks for processing sequential or structured text data.\",\n",
    "\n",
    "    # Transformers and Attention Models\n",
    "    \"Introduction to Transformers\": \"A model architecture using self-attention to handle sequence data.\",\n",
    "    \"Self-Attention Mechanism\": \"Mechanism to weigh the importance of different words in a sequence.\",\n",
    "    \"BERT (Bidirectional Encoder Representations from Transformers)\": \"Transformer model that understands text by looking both forward and backward.\",\n",
    "    \"GPT (Generative Pre-trained Transformer)\": \"Autoregressive transformer model for generating coherent text.\",\n",
    "    \"Transformer-Based Models (RoBERTa, ALBERT, T5, etc.)\": \"Variants of transformers optimized for different NLP tasks.\",\n",
    "    \"Fine-tuning Pre-trained Models\": \"Adapting a pre-trained model to a specific downstream NLP task.\",\n",
    "\n",
    "    # Evaluation Metrics\n",
    "    \"Accuracy, Precision, Recall, F1 Score\": \"Metrics to evaluate classification performance.\",\n",
    "    \"BLEU Score (for Translation)\": \"Metric to evaluate machine translation quality by n-gram overlap.\",\n",
    "    \"ROUGE Score (for Summarization)\": \"Measures overlap between generated and reference summaries.\",\n",
    "    \"Perplexity\": \"Evaluates how well a language model predicts a sequence.\",\n",
    "    \"Confusion Matrix\": \"A table to visualize model prediction performance across classes.\",\n",
    "\n",
    "    # Libraries and Tools\n",
    "    \"NLTK (Natural Language Toolkit)\": \"A Python library for basic NLP tasks and text processing.\",\n",
    "    \"spaCy\": \"Fast and industrial-strength NLP library with pretrained pipelines.\",\n",
    "    \"TextBlob\": \"Simplified library for NLP tasks like sentiment analysis and translation.\",\n",
    "    \"Gensim\": \"Library for topic modeling and document similarity analysis.\",\n",
    "    \"Scikit-learn for NLP\": \"ML library that provides tools for feature extraction and modeling text.\",\n",
    "    \"Hugging Face Transformers\": \"Library for using and fine-tuning transformer-based models.\",\n",
    "    \"Stanford NLP\": \"Suite of NLP tools developed by Stanford for deep analysis.\",\n",
    "    \"Flair NLP\": \"NLP framework built on PyTorch with simple APIs and powerful embeddings.\",\n",
    "\n",
    "    # Real-World Applications\n",
    "    \"Chatbots and Virtual Assistants\": \"Interactive systems that use NLP to simulate human conversation.\",\n",
    "    \"Search Engines\": \"Using NLP to understand queries and retrieve relevant information.\",\n",
    "    \"Spam Detection\": \"Identifying unwanted or harmful messages in communication platforms.\",\n",
    "    \"Plagiarism Detection\": \"Detecting copied or paraphrased content using text similarity.\",\n",
    "    \"Voice Assistants (Siri, Alexa)\": \"Speech-driven assistants that interpret and respond to commands.\",\n",
    "    \"Fake News Detection\": \"Identifying misleading or false information in text.\",\n",
    "    \"Document Classification\": \"Categorizing documents into predefined labels or topics.\",\n",
    "    \"Customer Feedback Analysis\": \"Analyzing reviews or feedback to extract insights and sentiment.\",\n",
    "\n",
    "    # Advanced and Research Topics\n",
    "    \"Zero-shot and Few-shot Learning in NLP\": \"Making predictions with little or no labeled data.\",\n",
    "    \"Multilingual NLP\": \"Building models that understand and process multiple languages.\",\n",
    "    \"Ethics in NLP\": \"Addressing privacy, consent, and misuse of language technology.\",\n",
    "    \"Bias and Fairness in Language Models\": \"Understanding and mitigating discrimination in NLP systems.\",\n",
    "    \"Prompt Engineering\": \"Designing effective prompts to control language model outputs.\",\n",
    "    \"Responsible AI in NLP\": \"Ensuring ethical, transparent, and fair NLP development and usage.\",\n",
    "\n",
    "    # Deployment and Integration\n",
    "    \"Saving and Loading NLP Models\": \"Persisting trained NLP models for reuse.\",\n",
    "    \"Deploying NLP Models with Flask / FastAPI\": \"Creating web APIs to serve NLP models.\",\n",
    "    \"Creating APIs for NLP Applications\": \"Exposing NLP functionality over web services for integration.\",\n",
    "    \"Using NLP in Production Systems\": \"Scaling and integrating NLP solutions in real-world systems.\",\n",
    "}\n",
    "\n",
    "\n",
    "data_science_topics = {\n",
    "    # Introduction & Foundations\n",
    "    \"What is Data Science\": \"An interdisciplinary field focused on extracting insights from data using scientific methods.\",\n",
    "    \"Data Science Lifecycle\": \"The end-to-end process of collecting, processing, analyzing, and deploying data solutions.\",\n",
    "    \"Data Science vs Data Analytics vs Machine Learning vs AI\": \"Comparing data-driven analysis, predictive modeling, and intelligent automation fields.\",\n",
    "    \"Real-World Applications of Data Science\": \"Practical uses of data science in industries like healthcare, finance, and marketing.\",\n",
    "\n",
    "    # Mathematics & Statistics\n",
    "    \"Descriptive Statistics (Mean, Median, Mode, Variance, Std Dev)\": \"Summarizing and describing key features of a dataset.\",\n",
    "    \"Probability Basics\": \"Fundamental concepts of chance and likelihood in uncertain events.\",\n",
    "    \"Bayes’ Theorem\": \"A formula to update probabilities based on new evidence.\",\n",
    "    \"Probability Distributions (Normal, Binomial, Poisson, etc.)\": \"Models describing how probabilities are distributed across values.\",\n",
    "    \"Inferential Statistics (Hypothesis Testing, p-values)\": \"Drawing conclusions about populations from sample data.\",\n",
    "    \"Correlation vs Causation\": \"Distinguishing between relationships and direct cause-effect links.\",\n",
    "    \"ANOVA\": \"Statistical method to compare means among multiple groups.\",\n",
    "    \"Linear Algebra (Vectors, Matrices, Eigenvalues)\": \"Mathematical tools for handling multidimensional data and transformations.\",\n",
    "    \"Calculus for Machine Learning (Derivatives, Gradients)\": \"Techniques to optimize functions and train models.\",\n",
    "\n",
    "    # Programming (Python Focused)\n",
    "    \"Python Basics (Variables, Loops, Functions)\": \"Core programming constructs to write Python code.\",\n",
    "    \"Data Structures in Python\": \"Organizing and storing data using lists, dictionaries, sets, and tuples.\",\n",
    "    \"Working with Files and Data Formats\": \"Reading and writing data in various file formats like CSV, JSON, and Excel.\",\n",
    "    \"List Comprehensions, Lambda, Map/Filter/Reduce\": \"Pythonic ways to manipulate collections efficiently.\",\n",
    "    \"Exception Handling\": \"Managing errors gracefully during program execution.\",\n",
    "    \"Object-Oriented Programming in Python\": \"Using classes and objects to design modular programs.\",\n",
    "\n",
    "    # Data Manipulation & Cleaning\n",
    "    \"Using NumPy for Numerical Computation\": \"Performing fast array operations and mathematical computations.\",\n",
    "    \"Using Pandas for DataFrames\": \"Handling and analyzing structured tabular data.\",\n",
    "    \"Handling Missing Data\": \"Techniques to detect and fill or remove incomplete data.\",\n",
    "    \"Data Type Conversion\": \"Changing data formats for proper processing and analysis.\",\n",
    "    \"Removing Duplicates\": \"Identifying and eliminating repeated records in datasets.\",\n",
    "    \"Dealing with Outliers\": \"Detecting and managing anomalous data points.\",\n",
    "    \"Data Normalization and Scaling\": \"Transforming data to comparable scales for modeling.\",\n",
    "    \"Encoding Categorical Variables\": \"Converting categories into numerical representations.\",\n",
    "    \"Parsing Dates and Times\": \"Extracting and manipulating temporal data.\",\n",
    "\n",
    "    # Data Visualization\n",
    "    \"Matplotlib Basics\": \"Creating static 2D plots and charts in Python.\",\n",
    "    \"Seaborn for Statistical Plots\": \"Building attractive and informative statistical visualizations.\",\n",
    "    \"Plotly for Interactive Visualization\": \"Generating dynamic, interactive charts for web use.\",\n",
    "    \"Histograms, Boxplots, Scatter Plots, Pair Plots\": \"Common plot types to explore data distributions and relationships.\",\n",
    "    \"Correlation Heatmaps\": \"Visualizing correlation strength between variables.\",\n",
    "    \"Dashboards with Power BI or Tableau\": \"Designing interactive business intelligence dashboards.\",\n",
    "    \"Geospatial Visualization (with Folium, GeoPandas)\": \"Mapping and analyzing spatial data.\",\n",
    "\n",
    "    # Exploratory Data Analysis (EDA)\n",
    "    \"Summary Statistics\": \"Calculating key metrics to understand data characteristics.\",\n",
    "    \"Univariate Analysis\": \"Analyzing the distribution of individual variables.\",\n",
    "    \"Bivariate and Multivariate Analysis\": \"Studying relationships among two or more variables.\",\n",
    "    \"Feature Relationships and Trends\": \"Detecting patterns and associations in data features.\",\n",
    "    \"Feature Distributions\": \"Examining how values of a feature spread across samples.\",\n",
    "    \"EDA Report Automation (e.g., Sweetviz, Pandas Profiling)\": \"Generating automated data exploration summaries.\",\n",
    "\n",
    "    # Machine Learning\n",
    "    \"Types of Machine Learning (Supervised, Unsupervised, Reinforcement)\": \"Categories of learning based on labeled data and feedback.\",\n",
    "    \"Train/Test Split\": \"Dividing data into sets for training and evaluating models.\",\n",
    "    \"Model Evaluation Metrics (Accuracy, F1, ROC-AUC)\": \"Quantitative measures of model performance.\",\n",
    "    \"Cross-Validation\": \"Technique to assess model generalization on unseen data.\",\n",
    "    \"Overfitting and Underfitting\": \"Balancing model complexity to avoid poor predictions.\",\n",
    "    \"Bias-Variance Tradeoff\": \"Managing error sources to improve model accuracy.\",\n",
    "\n",
    "    # Supervised Learning Algorithms\n",
    "    \"Linear Regression\": \"Modeling relationships between continuous variables.\",\n",
    "    \"Logistic Regression\": \"Predicting binary outcomes using a sigmoid function.\",\n",
    "    \"Decision Trees\": \"Tree-structured models for classification and regression.\",\n",
    "    \"Random Forests\": \"Ensemble of decision trees to improve predictive power.\",\n",
    "    \"K-Nearest Neighbors (KNN)\": \"Classifying based on nearest labeled data points.\",\n",
    "    \"Support Vector Machines (SVM)\": \"Finding the optimal boundary to separate classes.\",\n",
    "    \"Naive Bayes\": \"Probabilistic classifier assuming feature independence.\",\n",
    "    \"Gradient Boosting (XGBoost, LightGBM, CatBoost)\": \"Sequentially improved ensemble models for accuracy.\",\n",
    "\n",
    "    # Unsupervised Learning Algorithms\n",
    "    \"K-Means Clustering\": \"Partitioning data into k groups based on similarity.\",\n",
    "    \"Hierarchical Clustering\": \"Building nested clusters via a tree-like structure.\",\n",
    "    \"PCA (Principal Component Analysis)\": \"Reducing dimensionality by transforming features.\",\n",
    "    \"t-SNE and UMAP\": \"Visualizing high-dimensional data in low-dimensional spaces.\",\n",
    "    \"DBSCAN\": \"Density-based clustering identifying arbitrarily shaped groups.\",\n",
    "    \"Anomaly Detection\": \"Identifying unusual data points that deviate from patterns.\",\n",
    "\n",
    "    # Natural Language Processing (NLP)\n",
    "    \"Text Preprocessing\": \"Cleaning and preparing text data for analysis.\",\n",
    "    \"TF-IDF and Bag of Words\": \"Techniques to represent text as numerical features.\",\n",
    "    \"Sentiment Analysis\": \"Classifying emotions or opinions in text.\",\n",
    "    \"Text Classification\": \"Assigning predefined categories to text documents.\",\n",
    "    \"Topic Modeling (LDA)\": \"Discovering hidden themes within large text corpora.\",\n",
    "    \"Word Embeddings (Word2Vec, GloVe)\": \"Mapping words into continuous vector spaces.\",\n",
    "    \"Transformers and BERT (Intro)\": \"Advanced models for understanding contextual language.\",\n",
    "\n",
    "    # Time Series Analysis\n",
    "    \"Time Series Components (Trend, Seasonality)\": \"Identifying patterns in sequential data over time.\",\n",
    "    \"Lag Features and Rolling Statistics\": \"Using past values and moving averages for insights.\",\n",
    "    \"ARIMA and SARIMA Models\": \"Statistical models for forecasting time series data.\",\n",
    "    \"Facebook Prophet\": \"User-friendly tool for forecasting with seasonality and holidays.\",\n",
    "    \"Forecasting with Machine Learning\": \"Predicting future values using learning algorithms.\",\n",
    "\n",
    "    # Deep Learning (Intro to Intermediate)\n",
    "    \"Neural Networks Basics\": \"Computational models inspired by the human brain.\",\n",
    "    \"Activation Functions\": \"Functions that introduce non-linearity in networks.\",\n",
    "    \"Loss Functions\": \"Metrics that measure prediction errors during training.\",\n",
    "    \"Gradient Descent and Backpropagation\": \"Algorithms to optimize neural network weights.\",\n",
    "    \"CNNs (Convolutional Neural Networks)\": \"Specialized networks for image data processing.\",\n",
    "    \"RNNs and LSTMs for Sequences\": \"Models designed for sequential and time-dependent data.\",\n",
    "    \"Transfer Learning\": \"Reusing pre-trained models to solve new tasks.\",\n",
    "    \"Using TensorFlow and Keras\": \"Popular frameworks for building deep learning models.\",\n",
    "    \"PyTorch Basics\": \"Flexible deep learning library with dynamic computation graphs.\",\n",
    "\n",
    "    # Model Deployment & MLOps\n",
    "    \"Saving and Loading Models (Pickle, Joblib)\": \"Storing and retrieving trained models efficiently.\",\n",
    "    \"Building APIs with Flask or FastAPI\": \"Creating web services to serve machine learning models.\",\n",
    "    \"Streamlit for Model Demos\": \"Quickly building interactive data apps without frontend coding.\",\n",
    "    \"Docker for Model Deployment\": \"Containerizing applications for consistent environments.\",\n",
    "    \"MLflow and DVC for Experiment Tracking\": \"Tools for managing machine learning lifecycle and data versioning.\",\n",
    "    \"CI/CD Pipelines for ML Projects\": \"Automating testing and deployment of ML models.\",\n",
    "\n",
    "    # Big Data & Cloud (Intro Level)\n",
    "    \"Basics of Big Data and Hadoop Ecosystem\": \"Frameworks for processing large-scale distributed data.\",\n",
    "    \"Using PySpark for Distributed Data\": \"Python interface for large-scale data processing on clusters.\",\n",
    "    \"Introduction to SQL and NoSQL\": \"Querying structured and unstructured databases.\",\n",
    "    \"Cloud Platforms (AWS, GCP, Azure)\": \"Services for scalable computing and storage in the cloud.\",\n",
    "    \"Using Google Colab and Jupyter Notebooks\": \"Interactive environments for coding and sharing notebooks.\",\n",
    "\n",
    "    # Tools & Version Control\n",
    "    \"Jupyter Notebooks\": \"Web-based interface for interactive code, visualizations, and notes.\",\n",
    "    \"VS Code for Data Science\": \"Lightweight code editor with powerful data science extensions.\",\n",
    "    \"Git and GitHub\": \"Version control systems for managing and collaborating on code.\",\n",
    "    \"Conda/Virtualenv for Environments\": \"Tools to create isolated Python environments for projects.\",\n",
    "    \"Pip and Requirements.txt\": \"Package installer and dependency management for Python projects.\",\n",
    "\n",
    "    # Business and Soft Skills\n",
    "    \"Problem Formulation\": \"Defining the data science problem clearly for effective solutions.\",\n",
    "    \"Storytelling with Data\": \"Communicating insights through compelling narratives and visuals.\",\n",
    "    \"Presenting Insights to Stakeholders\": \"Effectively sharing data findings with decision-makers.\",\n",
    "    \"Domain Knowledge Integration\": \"Applying subject expertise to enhance data analysis relevance.\",\n",
    "    \"Ethics in Data Science\": \"Ensuring responsible and fair use of data and models.\",\n",
    "    \"Bias and Fairness in Models\": \"Detecting and mitigating unfair prejudices in algorithms.\",\n",
    "\n",
    "    # Projects and Case Studies\n",
    "    \"End-to-End Data Science Projects\": \"Complete workflows from data acquisition to deployment.\",\n",
    "    \"Kaggle Competitions\": \"Data science challenges to practice skills and compete globally.\",\n",
    "    \"Real-World Case Studies\": \"Examples showcasing data science solving practical problems.\",\n",
    "    \"Portfolio Building Tips\": \"Strategies to create a strong showcase of your data science work.\"\n",
    "}\n",
    "\n",
    "data_analyst_topics = {\n",
    "    # Introduction\n",
    "    \"What is Data Analysis\": \"The process of inspecting, cleaning, and interpreting data to gain insights.\",\n",
    "    \"Data Analyst vs Data Scientist vs BI Analyst\": \"Comparison of roles based on focus areas, skills, and outcomes.\",\n",
    "    \"Data Analysis Process (Ask, Prepare, Process, Analyze, Share, Act)\": \"A structured approach to conducting effective data analysis.\",\n",
    "\n",
    "    # Excel for Data Analysis\n",
    "    \"Basic Excel Functions (SUM, AVERAGE, COUNT, etc.)\": \"Common formulas to perform basic mathematical operations.\",\n",
    "    \"Logical Functions (IF, AND, OR)\": \"Functions used to apply decision logic in cells.\",\n",
    "    \"Lookup Functions (VLOOKUP, HLOOKUP, XLOOKUP, INDEX-MATCH)\": \"Retrieve data from other tables or ranges in Excel.\",\n",
    "    \"Text Functions (LEFT, RIGHT, MID, LEN, CONCATENATE)\": \"Manipulate and format text values.\",\n",
    "    \"Date and Time Functions\": \"Work with and calculate date/time values.\",\n",
    "    \"Conditional Formatting\": \"Highlight cells based on rules or conditions.\",\n",
    "    \"Data Validation and Dropdowns\": \"Restrict or control input values in cells.\",\n",
    "    \"Pivot Tables and Pivot Charts\": \"Summarize and analyze large datasets dynamically.\",\n",
    "    \"Excel Charts and Dashboards\": \"Visual representation of data using various chart types.\",\n",
    "    \"Power Query (Get & Transform)\": \"Tool to import, clean, and reshape data in Excel.\",\n",
    "    \"Power Pivot and Data Modeling in Excel\": \"Advanced modeling and analysis with data relationships and DAX.\",\n",
    "\n",
    "    # SQL for Data Analysts\n",
    "    \"SQL Basics (SELECT, WHERE, ORDER BY)\": \"Basic commands to query and sort data in databases.\",\n",
    "    \"Filtering and Sorting Data\": \"Retrieve only relevant records with filters and sort orders.\",\n",
    "    \"Joins (INNER, LEFT, RIGHT, FULL)\": \"Combine data from multiple tables based on relationships.\",\n",
    "    \"GROUP BY and Aggregate Functions\": \"Summarize data using COUNT, SUM, AVG, etc. grouped by fields.\",\n",
    "    \"HAVING vs WHERE\": \"Filter groups of data vs individual rows in SQL queries.\",\n",
    "    \"Subqueries and Nested Queries\": \"Queries inside other queries to retrieve intermediate results.\",\n",
    "    \"Common Table Expressions (CTEs)\": \"Temporary named result sets for readable and reusable SQL.\",\n",
    "    \"Window Functions (RANK, ROW_NUMBER, etc.)\": \"Perform calculations across rows related to the current row.\",\n",
    "    \"CASE Statements\": \"Write conditional logic within SQL queries.\",\n",
    "    \"Creating and Modifying Tables\": \"Build or update database tables with structure definitions.\",\n",
    "    \"Data Cleaning in SQL\": \"Transform and clean raw data using SQL functions and logic.\",\n",
    "\n",
    "    # Python for Data Analysis\n",
    "    \"Python Basics (Variables, Data Types, Control Flow)\": \"Core programming concepts required for data tasks.\",\n",
    "    \"Working with Pandas (DataFrames, Series)\": \"Use pandas library for handling tabular and labeled data.\",\n",
    "    \"Data Cleaning and Manipulation\": \"Fix, reshape, or transform data using pandas or NumPy.\",\n",
    "    \"Exploratory Data Analysis (EDA)\": \"Initial data investigation using stats and visualizations.\",\n",
    "    \"Data Visualization (Matplotlib, Seaborn)\": \"Generate plots to explore and present data.\",\n",
    "    \"Working with Date and Time in Python\": \"Handle and manipulate datetime values effectively.\",\n",
    "    \"Basic Statistics with Python\": \"Compute descriptive and inferential statistics using libraries.\",\n",
    "    \"Regular Expressions for Text Data\": \"Extract or clean text using pattern matching.\",\n",
    "    \"Using NumPy for Numerical Computation\": \"Perform fast numerical operations using arrays.\",\n",
    "    \"Loading and Saving Data (CSV, Excel, JSON)\": \"Import/export data using pandas and built-in libraries.\",\n",
    "\n",
    "    # Statistics & Mathematics\n",
    "    \"Descriptive Statistics (Mean, Median, Mode, Variance, Std Dev)\": \"Summarize and describe key aspects of datasets.\",\n",
    "    \"Probability Basics\": \"Understand chances and uncertainty in data.\",\n",
    "    \"Correlation and Covariance\": \"Measure relationships and dependencies between variables.\",\n",
    "    \"Distributions (Normal, Binomial, etc.)\": \"Understand patterns in how data is distributed.\",\n",
    "    \"Sampling Methods\": \"Techniques to draw representative subsets from a population.\",\n",
    "    \"Central Limit Theorem\": \"Theory that sample means approach a normal distribution.\",\n",
    "    \"Hypothesis Testing (p-value, t-test, z-test)\": \"Make decisions or inferences based on sample data.\",\n",
    "    \"Confidence Intervals\": \"Estimate range of values likely to include a population parameter.\",\n",
    "    \"A/B Testing\": \"Compare two versions of something to determine which performs better.\",\n",
    "    \"Regression Analysis Basics\": \"Predict numerical outcomes using independent variables.\",\n",
    "\n",
    "    # Data Visualization & Storytelling\n",
    "    \"Choosing the Right Chart\": \"Select visuals that best convey your message and data.\",\n",
    "    \"Bar, Line, Pie, Histogram, Boxplot, Heatmap\": \"Common chart types used in analysis and presentation.\",\n",
    "    \"Interactive Dashboards (Tableau / Power BI)\": \"Build user-friendly dashboards for insights delivery.\",\n",
    "    \"Data Storytelling Principles\": \"Craft clear and compelling narratives from data.\",\n",
    "    \"Designing for Clarity and Impact\": \"Create visuals that are easy to understand and actionable.\",\n",
    "    \"Color Theory in Visualizations\": \"Use color intentionally to enhance interpretation.\",\n",
    "\n",
    "    # Business Intelligence Tools (Power BI / Tableau)\n",
    "    \"Connecting to Data Sources\": \"Import data from various files, databases, or cloud services.\",\n",
    "    \"Data Cleaning and Shaping\": \"Transform and format data for analysis.\",\n",
    "    \"Data Modeling and Relationships\": \"Define how data tables are connected and interact.\",\n",
    "    \"Creating Visuals and Dashboards\": \"Design and display charts and KPIs in one place.\",\n",
    "    \"Slicers and Filters\": \"Allow users to interactively explore data subsets.\",\n",
    "    \"Using DAX (Power BI) or Calculated Fields (Tableau)\": \"Write formulas for calculated measures and fields.\",\n",
    "    \"Row-Level Security\": \"Restrict data visibility based on user roles.\",\n",
    "    \"Publishing and Sharing Reports\": \"Distribute dashboards to teams or stakeholders.\",\n",
    "    \"Drill-Down and Drill-Through\": \"Enable deeper exploration of visualized data.\",\n",
    "    \"Custom Visuals\": \"Add or build unique visual elements for storytelling.\",\n",
    "\n",
    "    # Google Sheets (Optional but Popular)\n",
    "    \"Functions and Formulas\": \"Perform calculations and automate tasks using built-in functions.\",\n",
    "    \"Pivot Tables\": \"Summarize data dynamically within Google Sheets.\",\n",
    "    \"Charts and Data Validation\": \"Visualize trends and control input values.\",\n",
    "    \"Google App Script Basics\": \"Automate tasks using JavaScript-based scripts in Sheets.\",\n",
    "\n",
    "    # Data Cleaning & Wrangling\n",
    "    \"Handling Missing Values\": \"Detect and fill, remove, or flag empty data entries.\",\n",
    "    \"Dealing with Outliers\": \"Identify and treat extreme values that may skew analysis.\",\n",
    "    \"Converting Data Types\": \"Change between string, int, float, datetime, etc.\",\n",
    "    \"Removing Duplicates\": \"Identify and drop redundant rows or entries.\",\n",
    "    \"Standardizing Data Formats\": \"Ensure consistency in how data is represented.\",\n",
    "    \"Splitting and Merging Columns\": \"Divide or combine data fields for analysis.\",\n",
    "    \"Detecting and Fixing Data Quality Issues\": \"Find inconsistencies, typos, or errors and clean them.\",\n",
    "\n",
    "    # Soft Skills & Business Knowledge\n",
    "    \"Understanding Business Requirements\": \"Clarify goals before analyzing data.\",\n",
    "    \"Problem Solving and Critical Thinking\": \"Apply logic to analyze and resolve data issues.\",\n",
    "    \"Stakeholder Communication\": \"Effectively share insights with non-technical audiences.\",\n",
    "    \"Data-Driven Decision Making\": \"Support business choices with evidence from data.\",\n",
    "    \"Agile and Project Management Basics\": \"Deliver analysis iteratively with clear timelines.\",\n",
    "    \"Writing Reports and Presenting Insights\": \"Document and communicate findings clearly.\",\n",
    "    \"Domain Knowledge (Marketing, Finance, HR, etc.)\": \"Contextual understanding to enhance relevance of insights.\",\n",
    "\n",
    "    # Data Ethics & Privacy\n",
    "    \"Data Privacy Laws (GDPR, CCPA)\": \"Legal frameworks for handling personal data.\",\n",
    "    \"Ethical Use of Data\": \"Use data responsibly and fairly.\",\n",
    "    \"Bias in Data Analysis\": \"Recognize and reduce unfair skew in insights.\",\n",
    "    \"Data Anonymization and Security\": \"Protect identities while working with sensitive data.\",\n",
    "\n",
    "    # Portfolio & Career Development\n",
    "    \"Building a Data Analyst Portfolio\": \"Showcase your work and skills to potential employers.\",\n",
    "    \"Creating Dashboards for Real Projects\": \"Demonstrate real-world problem-solving visually.\",\n",
    "    \"Interview Preparation (Behavioral + Technical)\": \"Practice common questions and case studies.\",\n",
    "    \"Resume and LinkedIn Optimization\": \"Market your skills effectively to recruiters.\",\n",
    "    \"Certifications (Google Data Analytics, Microsoft, etc.)\": \"Earn credentials to validate your expertise.\",\n",
    "    \"Contributing to Open Data Projects\": \"Gain experience and visibility by working with public data.\",\n",
    "    \"Kaggle and Other Platforms for Practice\": \"Participate in challenges to build skills and community.\",\n",
    "\n",
    "    # Tools & Technologies\n",
    "    \"Jupyter Notebooks\": \"Web-based environment for writing and sharing Python code.\",\n",
    "    \"Anaconda Environment\": \"Python distribution for managing data science packages.\",\n",
    "    \"Git and GitHub\": \"Version control and code collaboration tools.\",\n",
    "    \"Command Line Basics\": \"Use shell commands to interact with your system or data.\",\n",
    "    \"APIs and Data from Web\": \"Extract data from online services using APIs.\"}\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "17400597-7aa9-43af-ad27-775871f50ff6",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> PYTHON             </span> topic today : <span style=\"background-color: #000080\"> Operators </span><span style=\"background-color: #000080; font-weight: bold\">(</span><span style=\"background-color: #000080\">Arithmetic, Comparison, Logical, etc.</span><span style=\"background-color: #000080; font-weight: bold\">)</span><span style=\"background-color: #000080\"> </span> :\n",
       "                                Perform operations like addition, comparisons, and logical decisions.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m PYTHON             \u001b[0m topic today : \u001b[44m Operators \u001b[0m\u001b[1;44m(\u001b[0m\u001b[44mArithmetic, Comparison, Logical, etc.\u001b[0m\u001b[1;44m)\u001b[0m\u001b[44m \u001b[0m :\n",
       "                                Perform operations like addition, comparisons, and logical decisions.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> DATA SCIENCE       </span> topic today : <span style=\"background-color: #000080\"> Forecasting with Machine Learning        </span> :\n",
       "                                                  Predicting future values using learning algorithms.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m DATA SCIENCE       \u001b[0m topic today : \u001b[44m Forecasting with Machine Learning        \u001b[0m :\n",
       "                                                  Predicting future values using learning algorithms.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> DATA ANALYST       </span> topic today : <span style=\"background-color: #000080\"> Contributing to Open Data Projects       </span> :\n",
       "                                          Gain experience and visibility by working with public data.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m DATA ANALYST       \u001b[0m topic today : \u001b[44m Contributing to Open Data Projects       \u001b[0m :\n",
       "                                          Gain experience and visibility by working with public data.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> MACHINE LEARNING   </span> topic today : <span style=\"background-color: #000080\"> Recurrent Neural Networks </span><span style=\"background-color: #000080; font-weight: bold\">(</span><span style=\"background-color: #000080\">RNNs</span><span style=\"background-color: #000080; font-weight: bold\">)</span><span style=\"background-color: #000080\">         </span> :\n",
       "                                               Neural networks with loops to process sequential data.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m MACHINE LEARNING   \u001b[0m topic today : \u001b[44m Recurrent Neural Networks \u001b[0m\u001b[1;44m(\u001b[0m\u001b[44mRNNs\u001b[0m\u001b[1;44m)\u001b[0m\u001b[44m         \u001b[0m :\n",
       "                                               Neural networks with loops to process sequential data.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> SQL TOPICS         </span> topic today : <span style=\"background-color: #000080\"> Mathematical Functions                   </span> :\n",
       "                                              Performs arithmetic or mathematical operations on data.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m SQL TOPICS         \u001b[0m topic today : \u001b[44m Mathematical Functions                   \u001b[0m :\n",
       "                                              Performs arithmetic or mathematical operations on data.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> POWER BI TOPICS    </span> topic today : <span style=\"background-color: #000080\"> Power BI Embedded </span><span style=\"background-color: #000080; font-weight: bold\">(</span><span style=\"background-color: #000080\">for Developers</span><span style=\"background-color: #000080; font-weight: bold\">)</span><span style=\"background-color: #000080\">       </span> :\n",
       "                                         Embedding Power BI visuals in custom applications for users.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m POWER BI TOPICS    \u001b[0m topic today : \u001b[44m Power BI Embedded \u001b[0m\u001b[1;44m(\u001b[0m\u001b[44mfor Developers\u001b[0m\u001b[1;44m)\u001b[0m\u001b[44m       \u001b[0m :\n",
       "                                         Embedding Power BI visuals in custom applications for users.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"color: #ff0000; text-decoration-color: #ff0000\"> NLP                </span> topic today : <span style=\"background-color: #000080\"> Plagiarism Detection                     </span> :\n",
       "                                       Detecting copied or paraphrased content using text similarity.\n",
       "\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[91m NLP                \u001b[0m topic today : \u001b[44m Plagiarism Detection                     \u001b[0m :\n",
       "                                       Detecting copied or paraphrased content using text similarity.\n",
       "\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import random\n",
    "\n",
    "def print_topic(category_name, topic_dict):\n",
    "    key, value = random.choice(list(topic_dict.items()))\n",
    "    print(f\"[bright_red] {category_name.upper():<18} [/bright_red] topic today : [on blue] {key:<40} [/on blue] :\\n {value:>100}\\n\")\n",
    "\n",
    "print_topic(\"Python\", python_topics)\n",
    "print_topic(\"Data Science\", data_science_topics)\n",
    "print_topic(\"Data Analyst\", data_analyst_topics)\n",
    "print_topic(\"Machine Learning\", machine_learning_topics)\n",
    "print_topic(\"SQL Topics\", sql_topics)\n",
    "print_topic(\"Power BI Topics\", power_bi_topics)\n",
    "print_topic(\"NLP\", nlp_topics)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b6a0e221-4f46-4de6-a023-0ace2f7b18d0",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb4769b0-ccb4-4562-b29f-acbabf9b839d",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
